spring:
  profiles: default
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.turtlebone.top:3306/turtle?allowMultiQueries=true
    username: mysql
    password: mysql
    initialSize: 10
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    testWhileIdle: true
    validationQuery: select 'x'
  redis:
    database: 0
    hostName: 127.0.0.1
    port: 6379
    pool.max-idle: 8
    pool.min-idle: 0
    pool.max-active: 8
    pool.max-wait: -1
server:
  port: 12002
  contextPath: /sudoku/
mybatis:
  mapperLocations: classpath:mapper/*.xml
  #mapperLocations: classpath:com/turtle/sudoku/entity/*.xml
---
spring:
  profiles: prod
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.turtlebone.top:3306/turtle?allowMultiQueries=true
    username: mysql
    password: mysql
    initialSize: 10
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    testWhileIdle: true
    validationQuery: select 'x'
  redis:
    database: 0
    hostName: r-wz9dbc5c7dc742e4.redis.rds.aliyuncs.com
    password: Turtle2017
    port: 6379
    pool.max-idle: 8
    pool.min-idle: 0
    pool.max-active: 8
    pool.max-wait: -1
server:
  port: 12002
  contextPath: /sudoku/
mybatis:
  mapperLocations: classpath:mapper/*.xml
  #mapperLocations: classpath:com/turtle/sudoku/entity/*.xml