spring:
  profiles: default
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.29.24.34:3306/turtle?allowMultiQueries=true
    username: mysql
    password: mysql
    initialSize: 10
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    testWhileIdle: true
    validationQuery: select 'x'

server:
  port: 12002
  contextPath: /sudoku/
mybatis:
  mapperLocations: classpath:mapper/*.xml
  #mapperLocations: classpath:com/turtle/sudoku/entity/*.xml