spring:
  profiles: default
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.29.24.34:3306/turtle?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8&supportBigNumbers=true&useSSL=false
    username: mysql
    password: mysql
    initialSize: 10
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    testWhileIdle: true
    validationQuery: select 'x'
server:
  port: 12002
  contextPath: /sudoku/
mybatis:
  mapperLocations: classpath:mapper/*.xml